---
title: "Covid_review_figures"
author: "Weihan Liu"
date: "30/06/2020"
output: html_document
---

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(stats)
```


```{r}
covid_df <- read_excel("/Users/weihan/Desktop/华人抗体协会/covid_analysis/covid19_therapeutic_antibody/Data/Covid19_Ab_Track_20200808.xlsx")
str(covid_df)
```


#Target pie chart
##data processing
```{r,fig.height=7,fig.width=7}
library(ggrepel)
#create a new data frame containing the number of each target
target_pct <- table(covid_df$Target) %>%
        as.data.frame() %>%
        rename(Target = Var1,
               Amount = Freq)
target_pct$Target <- as.character(target_pct$Target)
#combine all of the targets that only have a value smaller or equal to 2 into "others"
target_pct <- rbind(target_pct,c("Others",sum(filter(target_pct,Amount <= 2)$Amount)))
target_pct$Amount <- as.numeric(target_pct$Amount)
target_pct <- filter(target_pct,Amount > 2) 

#compute percentage
target_pct$Percent <- round(target_pct$Amount/sum(target_pct$Amount) * 100,digits = 0) 

#compute cumulative percentage(top of each rectangle)
target_pct$y_max <- cumsum(target_pct$Percent)

#compute the bottom of each rectangle
target_pct$y_min <- c(0, head(target_pct$y_max, n=-1))

#compute the label position
target_pct$label_position <- (target_pct$y_max + target_pct$y_min)/2

# Compute a good label
target_pct$label <- paste0(target_pct$Target, ": ",target_pct$Amount, " (",target_pct$Percent,"%",")")

#create a column specifying the label color
target_pct <- target_pct %>% 
        mutate(label_color = c("#000000","#FFFFFF","#FFFFFF","#FFFFFF","#000000","#FFFFFF"))
```


##plot
```{r,fig.width=10,fig.height=10,out.width = "15in",fig.margin = TRUE}
#donut chart
#create your own palette, we have 6 categories, so choose 6 colors
my_cols = c("#EFC000FF","#1E90FF", "#CD853F","#868686FF", "#CD534CFF","#87CEFA")


ggplot(target_pct, aes(ymax=y_max, ymin=y_min, xmax=4, xmin=3, fill=Target)) +
  geom_rect() +
  geom_label_repel(x=3.5, aes(y=label_position, label=label), 
                   color = target_pct$label_color,
                   size=8,nudge_x = 0.5,segment.alpha = 0,
                   fontface = "bold") +
  scale_fill_manual(values =my_cols) +
  coord_polar(theta="y") +
 # xlim(c(1, 4)) +
  theme_void() +
  ggtitle("Targets") +
  theme(legend.position = "none",
  plot.title = element_text(vjust = 2,hjust = 0.5,face = "bold",size =30))+
  NULL


ggsave("Fig_2A_Targets_pie.tiff", dpi=300, height=7, width=7, units="in")
```

Make another version of the target Pie chart for cover image
```{r}
#give two examples of "others" category in the label
target_pct_cover <- target_pct
target_pct_cover$label[target_pct_cover$label == "Others: 47 (31%)"] <- "Others(TNF,IL-17A etc.): 47 (31%)"
  
#We will use red to highlight s protein and light blu colors to label the rest
my_cols_cover_target = c("#0080FF","#111E6C", "#0E4D92","#0F52BA","#008ECC","#CD534CFF")
#create a column specifying the label color
target_pct_cover <- target_pct_cover %>% 
        mutate(label_color_cover = c("#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"))


ggplot(target_pct_cover, aes(ymax=y_max, ymin=y_min, xmax=4, xmin=3, fill=Target)) +
  geom_rect() +
  geom_label_repel(x=3.5, aes(y=label_position, label=label), 
                   color = target_pct_cover$label_color_cover,
                   size=8,nudge_x = 0.5,segment.alpha = 0,
                   fontface = "bold") +
  scale_fill_manual(values =my_cols_cover_target) +
  coord_polar(theta="y") +
 # xlim(c(1, 4)) +
  theme_void() +
  ggtitle("Targets") +
  theme(legend.position = "none",
  plot.title = element_text(vjust = 2,hjust = 0.5,face = "bold",size =30))+
  NULL

ggsave("Fig_2A_Targets_pie_cover.jpg", dpi=600, height=7, width=7, units="in")
```




Format Donut chart
Data processing
```{r}
#subset out only the targets column
format_df <- select(covid_df,"Format")

#create a new data frame containing the number of each format
format_pct <- table(format_df$Format) %>%
        as.data.frame() %>%
        rename(Format = Var1,
               Amount = Freq)

format_pct$Format <- as.character(format_pct$Format)
format_pct$Amount <- as.numeric(format_pct$Amount)
#modify names to be consistent with capitalization
format_pct$Format <- Hmisc::capitalize(format_pct$Format)

#We will only list the major formats: mAb,polyclonal Abs,single-domain Ab,Bi-specific mAb,Tri-specific mAb,fusion protein. All other format will be listed as others, let's first calculate how many are in the others category
format_pct <- filter(format_pct,Format %in% c("MAb","Polyclonal Abs",
                     "Single-domain Ab",
                     "Bi-specific mAb","Tri-specific mAb",
                     "Fusion protein")) %>% tibble::add_row(Format = "Others",Amount = 4)

#compute percentage
format_pct$Percent <- round(format_pct$Amount/sum(format_pct$Amount) * 100,digits = 0) 

#compute cumulative percentage(top of each rectange)
format_pct$y_max <- cumsum(format_pct$Percent)

#compute the bottom of each rectangle
format_pct$y_min <- c(0, head(format_pct$y_max, n=-1))

#compute the label position
format_pct$label_position <- (format_pct$y_max + format_pct$y_min)/2

# Compute a good label
format_pct$label <- paste0(format_pct$Format, ": ",format_pct$Amount, " (",format_pct$Percent,"%",")")

#manually change the fusion protein label to 4%, just to make sure all the pct add up to 100%
format_pct$label[format_pct$label == "Fusion protein: 7 (5%)"] <- "Fusion protein: 7 (4%)"
```

Make the Donut Plot: Format
```{r,fig.width=10,fig.height=10,out.width = "15in",fig.margin = TRUE}
my_col_format <- c("#FFD700",#gold
                   "#FFA07A",#light salmon
                   "#87CEFA",#light sky blue
                       "#40E0D0",#turquoise
                       "#1E90FF",#dodger blue
                       "#800000",#marppn
                       "#D3D3D3") #light grey

#add a column specifying label color



format_pct <- format_pct %>% 
        mutate(label_color = c("#000000","#000000","#000000","#FFFFFF","#FFFFFF","#000000","#000000"))

ggplot(format_pct, aes(ymax=y_max, ymin=y_min, xmax=4, xmin=3, fill=Format)) +
  geom_rect() +
  geom_label_repel(x=3.5, aes(y=label_position, label=label),
                   color = format_pct$label_color,
                   size=7,nudge_y = 3.5,
                   box.padding = 0.8,
                   force = 10,
                   #segment.alpha = 0,
                   fontface = "bold",
                   show.legend = FALSE) +
  scale_fill_manual(values= my_col_format ) +
  coord_polar(theta="y") +
 # xlim(c(1, 4)) +
  theme_void() +
  ggtitle("Formats") +
  theme(legend.position = "none",
        plot.title = element_text(vjust = 2,hjust = 0.5,face = "bold",size =30))+
  NULL

ggsave("Fig_1B_Format_donut.jpg", dpi=300, height=7.5, width=7.5, units="in")
```





Clinical Status donut chart
```{r}
library(car)
#create a new data frame containing the number of each target
clinic_status_pct <- table(covid_df$Status) %>%
        as.data.frame() %>%
        rename(Status = Var1,
               Amount = Freq)

clinic_status_pct$Status <- as.character(clinic_status_pct$Status)
#get rid of the unknown status
clinic_status_pct <- filter(clinic_status_pct,Status != "Unknown")

#create a pordering column that index the different status in the correct order
clinic_status_pct <- cbind(clinic_status_pct,
                          c(10,3,1,4,5,9,6,7,8,2))
clinic_status_pct <- rename(clinic_status_pct,order ="c(10, 3, 1, 4, 5, 9, 6, 7, 8, 2)")
                                 

#sort clinic_status_pct by the index column
clinic_status_pct <- clinic_status_pct %>% 
        arrange(order) %>% 
        mutate(Status = factor(Status,Status))

#compute percentage
clinic_status_pct$Percent <- round(clinic_status_pct$Amount/sum(clinic_status_pct$Amount) * 100,digits = 0) 

#compute cumulative percentage(top of each rectange)
clinic_status_pct$y_max <- cumsum(clinic_status_pct$Percent)

#compute the bottom of each rectangle
clinic_status_pct$y_min <- c(0, head(clinic_status_pct$y_max, n=-1))

#compute the label position
clinic_status_pct$label_position <- (clinic_status_pct$y_max + clinic_status_pct$y_min)/2

# Compute a good label
clinic_status_pct$label <- paste0(clinic_status_pct$Status, ": ",clinic_status_pct$Amount, " (",clinic_status_pct$Percent,"%",")")


```

Make the Donut Plot
```{r,fig.height=10,fig.width=10, out.width = "10in"}
#continuous color scale, I have 10 levels, so 5 color on the blue scale and 5 color on the red scale
#my_col_cli_status <- c("#0080FF","#3399FF","#66B2FF","#99CCFF","#CCE5FF","#FFCCCC","#FF9999","#FF6666","#FF3333","#FF0000")
my_col_cli_status <- c("#191970","#4169E1","#1E90FF","#99CCFF","#87CEFA","#ADD8E6","#FFDAB9","#FFA07A","#FF6347","#B22222")

#add a column specifying label color

clinic_status_pct <-
        clinic_status_pct %>% 
        mutate(label_color = c("#FFFFFF","#FFFFFF","#FFFFFF","#000000","#000000","#000000","#000000","#000000","#FFFFFF","#FFFFFF"))

ggplot(clinic_status_pct, aes(ymax=y_max, ymin=y_min, xmax=4, xmin=3, fill=Status)) +
  geom_rect() +
  geom_label_repel(x=3.5, aes(y=label_position, label=label),
                   color = clinic_status_pct$label_color,
                   size=7,nudge_x = 0.4,force = 5,
                   segment.alpha = 0,
                   fontface = "bold") +
  scale_fill_manual(values= my_col_cli_status) +
  coord_polar(theta="y") +
  #xlim(c(1, 4)) +
  theme_void() +
  ggtitle("Development Status") +
  theme(legend.position = "none",
  plot.title = element_text(vjust = 2,hjust = 0.5,face = "bold",size =30))+
  NULL

ggsave("Fig_3A_Dev_status_donut.tiff", dpi=300, height=7.5, width=7.5, units="in")
```

#make another version of developmental status pie char for the cover
```{r}

clinic_status_pct_cover <- clinic_status_pct
my_col_cli_status_cover <- c("#fbd3d0","#f6c4bd","#f0b5ab","#eaa598","#e39687","#dc8775","#cd6a55","#ba4831","#a82512","#9e0500")

#add a column specifying label color

clinic_status_pct_cover <-
        clinic_status_pct_cover %>% 
        mutate(label_color_cover = c("#000000","#000000","#000000","#000000","#000000","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"))

ggplot(clinic_status_pct_cover, aes(ymax=y_max, ymin=y_min, xmax=4, xmin=3, fill=Status)) +
  geom_rect() +
  geom_label_repel(x=3.5, aes(y=label_position, label=label),
                   color = clinic_status_pct_cover$label_color_cover,
                   size=7,nudge_x = 0.4,force = 5,
                   segment.alpha = 0,
                   fontface = "bold") +
  scale_fill_manual(values= my_col_cli_status_cover ) +
  coord_polar(theta="y") +
  #xlim(c(1, 4)) +
  theme_void() +
  ggtitle("Development Status") +
  theme(legend.position = "none",
  plot.title = element_text(vjust = 2,hjust = 0.5,face = "bold",size =30))+
  NULL

ggsave("Fig_2A_Dev_status_pie_cover.tiff", dpi=600, height=7, width=7, units="in")
```




