---
title: "covid19_visualisation"
author: "Weihan Liu"
date: "19/05/2020"
output: html_document
---

```{r}
library(RCurl) #for fetching google spreadsheet data
library(mosaic)
library(tidyr)
library(readxl)
# covid <- getURL("https://docs.google.com/spreadsheets/d/e/2PACX-1vRcKtlvdTC90b8Qs0SMoqFmfXPiEjAwzA_gZ_nsqZEvjA0htzCr1HeAMKdfeeMH7nFyz1p-F4_Lmj1W/pub?output=csv")
# covid <- read.csv(textConnection(covid))
covid <- read_excel("/Users/weihan/Desktop/华人抗体协会/covid_analysis/covid19_therapeutic_antibody/Data/Covid19_Ab_Track_20200808.xlsx")
covid <- as.data.frame(covid)
```


Country Analysis
```{r}
country <- covid %>%
        dplyr::select(c("Country","Status","Developer/Reseacher","Target"))

country <- separate(country,Country,into =
             c("1","2","3","4","5","6","7","8","9","10"))
str(country)
```

```{r}
sub_piece <- country[c(1,11,12,13)]
for (i in 2:(ncol(country)-3)) {
    sub_piece_next <- country[c(i,11,12,13)]
    names(sub_piece) <- names(sub_piece_next) 
    sub_piece <- rbind(sub_piece,sub_piece_next)
}

sub_piece <- sub_piece %>% 
    dplyr::rename(country = "10") %>%
    data.table::setorder(country) %>%
    filter(is.na(country) == FALSE)
    
#get rid of unknown clinical status
sub_piece <- filter(sub_piece, Status != "Unknown") %>% na.omit()
#add a counter column
sub_piece <- mutate(sub_piece,count = 1)



sub_piece <- sub_piece %>% filter(country != "South") 
sub_piece[sub_piece == "Korea"] <- "South Korea"
sub_piece <- sub_piece %>% filter(country != "UL") 

table(sub_piece$Status)
table(sub_piece$country)

#get rid of the NA rows
sub_piece <- sub_piece[!is.na(sub_piece$Status),]
```
Plotting
```{r}
library(plotly)
library(viridis)
library(hrbrthemes)
library(forcats)

#order the clinical status column
sub_piece$Status <- factor(sub_piece$Status, levels = c("Approved","Phase 1/2/3","Phase 3","Phase 2/3","Phase 2","Phase 1/2","Phase 1","Clinical pending","Preclinical","Discovery"))

country_plot <- ggplot(data = sub_piece, aes(x = fct_infreq(country), y = count, fill = Status)) + 
    geom_bar(position = "stack",stat = "identity") +
    #scale_fill_viridis(discrete = T,direction = -1) +
    #theme_ipsum() +
    scale_fill_brewer(palette ="RdBu") +
    theme_classic()+
    theme(axis.text.x=element_text(size = 11,angle=45, hjust=1,face = "bold"),
          axis.text.y=element_text(size = 12,face = "bold"),
          axis.title = element_text(size = 12)) + 
    ylab("Numbers in Development") +
    xlab("Countries") +
    ggtitle("Development Status by Country") +
    theme(plot.title = element_text(vjust = 2,hjust = 0.5,face = "bold",size = 15))+
    theme(legend.title = element_text(size = 12,face = 'bold'),
          legend.text = element_text(size = 10)) +
    coord_cartesian(ylim = c(0, 80))
    
  
country_plot
ggsave("Fig_3B_Dev_status_by_country.jpg", dpi=300, height=5, width=7.5, units="in")
```






Just plot the total number of Ab in devlopment for each country without clinical status information
```{r}
#extract the country column as a vector
country_vec <- country$Country

#split the rows with multiple countries by their seperator "/" anbd update the country vector
country_vec <- strsplit(country_vec,split = "/") %>% unlist() 

country_vec <- as.data.frame(table(country_vec)) 

country <- dplyr::rename(country_vec,
                      Country = country_vec,
                      number_in_development = Freq)


#order by the value of  number_in_development
country <- country[order(country$number_in_development,decreasing = TRUE),]

```

Plotting using plotly
```{r}
library(plotly)

country_plot <- ggplot(data = country, aes(x = Country, y = number_in_development)) +                    
                geom_bar(stat = "identity",fill='steelblue') +
                theme(axis.text.x=element_text(angle=45, hjust=1)) + 
                ylab("numbers in development") +
                xlab("Countries") +
                ggtitle("Numbers of Therapeutics Antibodies in Development by country")

country_fig <- ggplotly(country_plot)

country_fig



htmlwidgets::saveWidget(country_fig, file = "/Users/weihan/Desktop/by_country.html")        
```

build a plotly dash
```{r}
library(dash)
library(dashCoreComponents)
library(dashHtmlComponents)

app <- Dash$new()
app$layout(
    htmlDiv(
        list(
            dccGraph(figure=country_fig) 
        )
     )
)

app$run_server(debug=TRUE, dev_tools_hot_reload=FALSE)
```

